/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package atm;
public class App {
    public static void main(String[] args) {
        System.out.println("what would you like to do");
        System.out.println("select an  options");
        System.out.println("1.Check balance");
        System.out.println("2.Withdraw");
        System.out.println("3.Deposit");
       
    }
}
